# Generated by Django 4.1.3 on 2023-01-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_game_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='playing',
            field=models.BooleanField(default=False),
        ),
    ]
